bug:
  - "bug"               
  - "fix"               

feature:
  - "feature"           
  - "enhancement"       

documentation:
  - "docs"             
  - "documentation"     

question:
  - "question"          
  - "help"              
