name: Auto Label Issues

on:
  issues:
    types:
      - opened
      - edited

jobs:
  auto_label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Apply Labels
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
