name: Greetings

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Welcome @${{ github.actor }}! 🎉 Thank you for opening your first issue! We’re excited to have you contribute to this project! Please check our [Contributing Guidelines](https://github.com/Lelin07/retro-green-theme/blob/main/CONTRIBUTING.md)."

  auto-assign:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request == null
    steps:
      - name: Check for /assign comment
        id: check_comment
        run: |
          if [[ "${{ github.event.comment.body }}" == "/assign" ]]; then
            echo "::set-output name=assign::true"
          else
            echo "::set-output name=assign::false"
          fi

      - name: Assign user
        if: steps.check_comment.outputs.assign == 'true'
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}

  issue-auto-reply:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-reply to new issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.issue.number;
            const issueComment = "Thank you for opening this issue! We will review it as soon as possible. If you have any additional details or updates, feel free to add them here.";
            await github.issues.createComment({
              ...context.repo,
              issue_number: issueNumber,
              body: issueComment
            });
